### ISSUE TITLE
Unable to bind extras

### ISSUE THREAD

**Issue by DanteAndroid** [TheFinestArtist/AndroidBaseUtils#32]
```
05-23 23:35:25.698 16106-16106/top.navyblue.leandemo E/AndroidRuntime: FATAL EXCEPTION: main
                                                                       Process: top.navyblue.leandemo, PID: 16106
                                                                       java.lang.RuntimeException: Unable to bind extras for top.navyblue.leandemo.LoginActivity@1cb0ff52
                                                                           at com.thefinestartist.binders.ExtrasBinder.bindObject(ExtrasBinder.java:51)
                                                                           at com.thefinestartist.binders.ExtrasBinder.bind(ExtrasBinder.java:24)
                                                                           at top.navyblue.leandemo.LoginActivity.onNewIntent(LoginActivity.java:60)
                                                                           at android.app.Instrumentation.callActivityOnNewIntent(Instrumentation.java:1211)
                                                                           at android.app.Instrumentation.callActivityOnNewIntent(Instrumentation.java:1223)
                                                                           at android.app.ActivityThread.deliverNewIntents(ActivityThread.java:2456)
                                                                           at android.app.ActivityThread.performNewIntents(ActivityThread.java:2468)
                                                                           at android.app.ActivityThread.handleNewIntent(ActivityThread.java:2477)
                                                                           at android.app.ActivityThread.access$1600(ActivityThread.java:151)
                                                                           at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1375)
                                                                           at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                           at android.os.Looper.loop(Looper.java:135)
                                                                           at android.app.ActivityThread.main(ActivityThread.java:5254)
                                                                           at java.lang.reflect.Method.invoke(Native Method)
                                                                           at java.lang.reflect.Method.invoke(Method.java:372)
                                                                           at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
                                                                           at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)
                                                                        Caused by: java.lang.reflect.InvocationTargetException
                                                                           at java.lang.reflect.Method.invoke(Native Method)
                                                                           at java.lang.reflect.Method.invoke(Method.java:372)
                                                                           at com.thefinestartist.binders.ExtrasBinder.bindObject(ExtrasBinder.java:45)
                                                                           at com.thefinestartist.binders.ExtrasBinder.bind(ExtrasBinder.java:24) 
                                                                           at top.navyblue.leandemo.LoginActivity.onNewIntent(LoginActivity.java:60) 
                                                                           at android.app.Instrumentation.callActivityOnNewIntent(Instrumentation.java:1211) 
                                                                           at android.app.Instrumentation.callActivityOnNewIntent(Instrumentation.java:1223) 
                                                                           at android.app.ActivityThread.deliverNewIntents(ActivityThread.java:2456) 
                                                                           at android.app.ActivityThread.performNewIntents(ActivityThread.java:2468) 
                                                                           at android.app.ActivityThread.handleNewIntent(ActivityThread.java:2477) 
                                                                           at android.app.ActivityThread.access$1600(ActivityThread.java:151) 
                                                                           at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1375) 
                                                                           at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                           at android.os.Looper.loop(Looper.java:135) 
                                                                           at android.app.ActivityThread.main(ActivityThread.java:5254) 
                                                                           at java.lang.reflect.Method.invoke(Native Method) 
                                                                           at java.lang.reflect.Method.invoke(Method.java:372) 
                                                                           at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903) 
                                                                           at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698) 
                                                                        Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Object android.os.Bundle.get(java.lang.String)' on a null object reference
                                                                           at top.navyblue.leandemo.LoginActivity$$ExtraBinder.bind(LoginActivity$$ExtraBinder.java:8)
                                                                           at java.lang.reflect.Method.invoke(Native Method) 
                                                                           at java.lang.reflect.Method.invoke(Method.java:372) 
                                                                           at com.thefinestartist.binders.ExtrasBinder.bindObject(ExtrasBinder.java:45) 
                                                                           at com.thefinestartist.binders.ExtrasBinder.bind(ExtrasBinder.java:24) 
                                                                           at top.navyblue.leandemo.LoginActivity.onNewIntent(LoginActivity.java:60) 
                                                                           at android.app.Instrumentation.callActivityOnNewIntent(Instrumentation.java:1211) 
                                                                           at android.app.Instrumentation.callActivityOnNewIntent(Instrumentation.java:1223) 
                                                                           at android.app.ActivityThread.deliverNewIntents(ActivityThread.java:2456) 
                                                                           at android.app.ActivityThread.performNewIntents(ActivityThread.java:2468) 
                                                                           at android.app.ActivityThread.handleNewIntent(ActivityThread.java:2477) 
                                                                           at android.app.ActivityThread.access$1600(ActivityThread.java:151) 
                                                                           at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1375) 
                                                                           at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                           at android.os.Looper.loop(Looper.java:135) 
                                                                           at android.app.ActivityThread.main(ActivityThread.java:5254) 
                                                                           at java.lang.reflect.Method.invoke(Native Method) 
                                                                           at java.lang.reflect.Method.invoke(Method.java:372) 
                                                                           at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903) 
                                                                           at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698) 

```

**Comment by DanteAndroid** [comment]
Code:
```
    @Extra
    String user;
    @Extra
    String pwd;

...

    @Override
    protected void onNewIntent(Intent intent) {
        super.onNewIntent(intent);
        ExtrasBinder.bind(this);
        login(user, pwd);
    }
```
Intent:
```
        Intent intent = new Intent(getApplicationContext(), LoginActivity.class);
        intent.putExtra("user", phoneNum.getText().toString());
        intent.putExtra("pwd", phoneNum.getText().toString());
        startActivity(intent);
```

**Comment by DanteAndroid** [comment]
I remember yesterday it can run. So weird.
